package com.sgcc.epri.dataexchangeplatform.ProtoJava;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExchangePlfMonitorMsg.proto

public final class ExchangePlfMonitorMsg {
  private ExchangePlfMonitorMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface excplf_monitor_infoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:excplf_monitor_info)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *��Ӧ�����ʶ��UUID����Դ���ݶ���д��Ŀ��˺���������ӣ�
     * </pre>
     *
     * <code>optional string task_uuid = 1;</code>
     */
    boolean hasTaskUuid();
    /**
     * <pre>
     *��Ӧ�����ʶ��UUID����Դ���ݶ���д��Ŀ��˺���������ӣ�
     * </pre>
     *
     * <code>optional string task_uuid = 1;</code>
     */
    String getTaskUuid();
    /**
     * <pre>
     *��Ӧ�����ʶ��UUID����Դ���ݶ���д��Ŀ��˺���������ӣ�
     * </pre>
     *
     * <code>optional string task_uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getTaskUuidBytes();

    /**
     * <pre>
     *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
     * </pre>
     *
     * <code>required string uuid = 2;</code>
     */
    boolean hasUuid();
    /**
     * <pre>
     *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
     * </pre>
     *
     * <code>required string uuid = 2;</code>
     */
    String getUuid();
    /**
     * <pre>
     *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
     * </pre>
     *
     * <code>required string uuid = 2;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <pre>
     *������Ϣ����Ψһ��ʶ��UUID��
     * </pre>
     *
     * <code>required string data_uuid = 3;</code>
     */
    boolean hasDataUuid();
    /**
     * <pre>
     *������Ϣ����Ψһ��ʶ��UUID��
     * </pre>
     *
     * <code>required string data_uuid = 3;</code>
     */
    String getDataUuid();
    /**
     * <pre>
     *������Ϣ����Ψһ��ʶ��UUID��
     * </pre>
     *
     * <code>required string data_uuid = 3;</code>
     */
    com.google.protobuf.ByteString
        getDataUuidBytes();

    /**
     * <pre>
     *Դ��������ʱ�䣨Ŀ��˴���ʱ�䣩����ȷ���룬��1970�꿪ʼ
     * </pre>
     *
     * <code>required int64 occur_time = 4;</code>
     */
    boolean hasOccurTime();
    /**
     * <pre>
     *Դ��������ʱ�䣨Ŀ��˴���ʱ�䣩����ȷ���룬��1970�꿪ʼ
     * </pre>
     *
     * <code>required int64 occur_time = 4;</code>
     */
    long getOccurTime();

    /**
     * <pre>
     *Դ���ݶ��������ݼ�¼����Ŀ����յ�����Ϣ����¼����
     * </pre>
     *
     * <code>required int32 record_num = 5;</code>
     */
    boolean hasRecordNum();
    /**
     * <pre>
     *Դ���ݶ��������ݼ�¼����Ŀ����յ�����Ϣ����¼����
     * </pre>
     *
     * <code>required int32 record_num = 5;</code>
     */
    int getRecordNum();

    /**
     * <pre>
     *��Ϣ���ĵĴ�С
     * </pre>
     *
     * <code>required int32 msg_len = 6;</code>
     */
    boolean hasMsgLen();
    /**
     * <pre>
     *��Ϣ���ĵĴ�С
     * </pre>
     *
     * <code>required int32 msg_len = 6;</code>
     */
    int getMsgLen();

    /**
     * <pre>
     *Ŀ�������¼��
     * </pre>
     *
     * <code>optional int32 save_record_num = 7;</code>
     */
    boolean hasSaveRecordNum();
    /**
     * <pre>
     *Ŀ�������¼��
     * </pre>
     *
     * <code>optional int32 save_record_num = 7;</code>
     */
    int getSaveRecordNum();

    /**
     * <pre>
     *�������� ��0--������1--����
     * </pre>
     *
     * <code>optional int32 flag = 8;</code>
     */
    boolean hasFlag();
    /**
     * <pre>
     *�������� ��0--������1--����
     * </pre>
     *
     * <code>optional int32 flag = 8;</code>
     */
    int getFlag();

    /**
     * <pre>
     *��Դ ��0--Դ���ݶˣ�1--Ŀ���
     * </pre>
     *
     * <code>required int32 origin_flag = 9;</code>
     */
    boolean hasOriginFlag();
    /**
     * <pre>
     *��Դ ��0--Դ���ݶˣ�1--Ŀ���
     * </pre>
     *
     * <code>required int32 origin_flag = 9;</code>
     */
    int getOriginFlag();
  }
  /**
   * <pre>
   *Դ���ݶ˼�����Ϣ
   * </pre>
   *
   * Protobuf type {@code excplf_monitor_info}
   */
  public  static final class excplf_monitor_info extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:excplf_monitor_info)
      excplf_monitor_infoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use excplf_monitor_info.newBuilder() to construct.
    private excplf_monitor_info(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private excplf_monitor_info() {
      taskUuid_ = "";
      uuid_ = "";
      dataUuid_ = "";
      occurTime_ = 0L;
      recordNum_ = 0;
      msgLen_ = 0;
      saveRecordNum_ = 0;
      flag_ = 0;
      originFlag_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private excplf_monitor_info(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              taskUuid_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              uuid_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              dataUuid_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              occurTime_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              recordNum_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              msgLen_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              saveRecordNum_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              flag_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              originFlag_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ExchangePlfMonitorMsg.internal_static_excplf_monitor_info_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ExchangePlfMonitorMsg.internal_static_excplf_monitor_info_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              excplf_monitor_info.class, Builder.class);
    }

    private int bitField0_;
    public static final int TASK_UUID_FIELD_NUMBER = 1;
    private volatile Object taskUuid_;
    /**
     * <pre>
     *��Ӧ�����ʶ��UUID����Դ���ݶ���д��Ŀ��˺���������ӣ�
     * </pre>
     *
     * <code>optional string task_uuid = 1;</code>
     */
    public boolean hasTaskUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *��Ӧ�����ʶ��UUID����Դ���ݶ���д��Ŀ��˺���������ӣ�
     * </pre>
     *
     * <code>optional string task_uuid = 1;</code>
     */
    public String getTaskUuid() {
      Object ref = taskUuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taskUuid_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *��Ӧ�����ʶ��UUID����Դ���ݶ���д��Ŀ��˺���������ӣ�
     * </pre>
     *
     * <code>optional string task_uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTaskUuidBytes() {
      Object ref = taskUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        taskUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UUID_FIELD_NUMBER = 2;
    private volatile Object uuid_;
    /**
     * <pre>
     *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
     * </pre>
     *
     * <code>required string uuid = 2;</code>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
     * </pre>
     *
     * <code>required string uuid = 2;</code>
     */
    public String getUuid() {
      Object ref = uuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
     * </pre>
     *
     * <code>required string uuid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_UUID_FIELD_NUMBER = 3;
    private volatile Object dataUuid_;
    /**
     * <pre>
     *������Ϣ����Ψһ��ʶ��UUID��
     * </pre>
     *
     * <code>required string data_uuid = 3;</code>
     */
    public boolean hasDataUuid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *������Ϣ����Ψһ��ʶ��UUID��
     * </pre>
     *
     * <code>required string data_uuid = 3;</code>
     */
    public String getDataUuid() {
      Object ref = dataUuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dataUuid_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *������Ϣ����Ψһ��ʶ��UUID��
     * </pre>
     *
     * <code>required string data_uuid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDataUuidBytes() {
      Object ref = dataUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dataUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OCCUR_TIME_FIELD_NUMBER = 4;
    private long occurTime_;
    /**
     * <pre>
     *Դ��������ʱ�䣨Ŀ��˴���ʱ�䣩����ȷ���룬��1970�꿪ʼ
     * </pre>
     *
     * <code>required int64 occur_time = 4;</code>
     */
    public boolean hasOccurTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *Դ��������ʱ�䣨Ŀ��˴���ʱ�䣩����ȷ���룬��1970�꿪ʼ
     * </pre>
     *
     * <code>required int64 occur_time = 4;</code>
     */
    public long getOccurTime() {
      return occurTime_;
    }

    public static final int RECORD_NUM_FIELD_NUMBER = 5;
    private int recordNum_;
    /**
     * <pre>
     *Դ���ݶ��������ݼ�¼����Ŀ����յ�����Ϣ����¼����
     * </pre>
     *
     * <code>required int32 record_num = 5;</code>
     */
    public boolean hasRecordNum() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     *Դ���ݶ��������ݼ�¼����Ŀ����յ�����Ϣ����¼����
     * </pre>
     *
     * <code>required int32 record_num = 5;</code>
     */
    public int getRecordNum() {
      return recordNum_;
    }

    public static final int MSG_LEN_FIELD_NUMBER = 6;
    private int msgLen_;
    /**
     * <pre>
     *��Ϣ���ĵĴ�С
     * </pre>
     *
     * <code>required int32 msg_len = 6;</code>
     */
    public boolean hasMsgLen() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     *��Ϣ���ĵĴ�С
     * </pre>
     *
     * <code>required int32 msg_len = 6;</code>
     */
    public int getMsgLen() {
      return msgLen_;
    }

    public static final int SAVE_RECORD_NUM_FIELD_NUMBER = 7;
    private int saveRecordNum_;
    /**
     * <pre>
     *Ŀ�������¼��
     * </pre>
     *
     * <code>optional int32 save_record_num = 7;</code>
     */
    public boolean hasSaveRecordNum() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     *Ŀ�������¼��
     * </pre>
     *
     * <code>optional int32 save_record_num = 7;</code>
     */
    public int getSaveRecordNum() {
      return saveRecordNum_;
    }

    public static final int FLAG_FIELD_NUMBER = 8;
    private int flag_;
    /**
     * <pre>
     *�������� ��0--������1--����
     * </pre>
     *
     * <code>optional int32 flag = 8;</code>
     */
    public boolean hasFlag() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <pre>
     *�������� ��0--������1--����
     * </pre>
     *
     * <code>optional int32 flag = 8;</code>
     */
    public int getFlag() {
      return flag_;
    }

    public static final int ORIGIN_FLAG_FIELD_NUMBER = 9;
    private int originFlag_;
    /**
     * <pre>
     *��Դ ��0--Դ���ݶˣ�1--Ŀ���
     * </pre>
     *
     * <code>required int32 origin_flag = 9;</code>
     */
    public boolean hasOriginFlag() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <pre>
     *��Դ ��0--Դ���ݶˣ�1--Ŀ���
     * </pre>
     *
     * <code>required int32 origin_flag = 9;</code>
     */
    public int getOriginFlag() {
      return originFlag_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDataUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOccurTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRecordNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgLen()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOriginFlag()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskUuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dataUuid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, occurTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, recordNum_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, msgLen_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, saveRecordNum_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, flag_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, originFlag_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskUuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dataUuid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, occurTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, recordNum_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, msgLen_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, saveRecordNum_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, flag_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, originFlag_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof excplf_monitor_info)) {
        return super.equals(obj);
      }
      excplf_monitor_info other = (excplf_monitor_info) obj;

      boolean result = true;
      result = result && (hasTaskUuid() == other.hasTaskUuid());
      if (hasTaskUuid()) {
        result = result && getTaskUuid()
            .equals(other.getTaskUuid());
      }
      result = result && (hasUuid() == other.hasUuid());
      if (hasUuid()) {
        result = result && getUuid()
            .equals(other.getUuid());
      }
      result = result && (hasDataUuid() == other.hasDataUuid());
      if (hasDataUuid()) {
        result = result && getDataUuid()
            .equals(other.getDataUuid());
      }
      result = result && (hasOccurTime() == other.hasOccurTime());
      if (hasOccurTime()) {
        result = result && (getOccurTime()
            == other.getOccurTime());
      }
      result = result && (hasRecordNum() == other.hasRecordNum());
      if (hasRecordNum()) {
        result = result && (getRecordNum()
            == other.getRecordNum());
      }
      result = result && (hasMsgLen() == other.hasMsgLen());
      if (hasMsgLen()) {
        result = result && (getMsgLen()
            == other.getMsgLen());
      }
      result = result && (hasSaveRecordNum() == other.hasSaveRecordNum());
      if (hasSaveRecordNum()) {
        result = result && (getSaveRecordNum()
            == other.getSaveRecordNum());
      }
      result = result && (hasFlag() == other.hasFlag());
      if (hasFlag()) {
        result = result && (getFlag()
            == other.getFlag());
      }
      result = result && (hasOriginFlag() == other.hasOriginFlag());
      if (hasOriginFlag()) {
        result = result && (getOriginFlag()
            == other.getOriginFlag());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTaskUuid()) {
        hash = (37 * hash) + TASK_UUID_FIELD_NUMBER;
        hash = (53 * hash) + getTaskUuid().hashCode();
      }
      if (hasUuid()) {
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
      }
      if (hasDataUuid()) {
        hash = (37 * hash) + DATA_UUID_FIELD_NUMBER;
        hash = (53 * hash) + getDataUuid().hashCode();
      }
      if (hasOccurTime()) {
        hash = (37 * hash) + OCCUR_TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getOccurTime());
      }
      if (hasRecordNum()) {
        hash = (37 * hash) + RECORD_NUM_FIELD_NUMBER;
        hash = (53 * hash) + getRecordNum();
      }
      if (hasMsgLen()) {
        hash = (37 * hash) + MSG_LEN_FIELD_NUMBER;
        hash = (53 * hash) + getMsgLen();
      }
      if (hasSaveRecordNum()) {
        hash = (37 * hash) + SAVE_RECORD_NUM_FIELD_NUMBER;
        hash = (53 * hash) + getSaveRecordNum();
      }
      if (hasFlag()) {
        hash = (37 * hash) + FLAG_FIELD_NUMBER;
        hash = (53 * hash) + getFlag();
      }
      if (hasOriginFlag()) {
        hash = (37 * hash) + ORIGIN_FLAG_FIELD_NUMBER;
        hash = (53 * hash) + getOriginFlag();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static excplf_monitor_info parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static excplf_monitor_info parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static excplf_monitor_info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static excplf_monitor_info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static excplf_monitor_info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static excplf_monitor_info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static excplf_monitor_info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static excplf_monitor_info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static excplf_monitor_info parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static excplf_monitor_info parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static excplf_monitor_info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static excplf_monitor_info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(excplf_monitor_info prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *Դ���ݶ˼�����Ϣ
     * </pre>
     *
     * Protobuf type {@code excplf_monitor_info}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:excplf_monitor_info)
        excplf_monitor_infoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ExchangePlfMonitorMsg.internal_static_excplf_monitor_info_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ExchangePlfMonitorMsg.internal_static_excplf_monitor_info_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                excplf_monitor_info.class, Builder.class);
      }

      // Construct using ExchangePlfMonitorMsg.excplf_monitor_info.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        taskUuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        dataUuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        occurTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        recordNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        msgLen_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        saveRecordNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        flag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        originFlag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ExchangePlfMonitorMsg.internal_static_excplf_monitor_info_descriptor;
      }

      public excplf_monitor_info getDefaultInstanceForType() {
        return excplf_monitor_info.getDefaultInstance();
      }

      public excplf_monitor_info build() {
        excplf_monitor_info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public excplf_monitor_info buildPartial() {
        excplf_monitor_info result = new excplf_monitor_info(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.taskUuid_ = taskUuid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dataUuid_ = dataUuid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.occurTime_ = occurTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.recordNum_ = recordNum_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.msgLen_ = msgLen_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.saveRecordNum_ = saveRecordNum_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.flag_ = flag_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.originFlag_ = originFlag_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof excplf_monitor_info) {
          return mergeFrom((excplf_monitor_info)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(excplf_monitor_info other) {
        if (other == excplf_monitor_info.getDefaultInstance()) return this;
        if (other.hasTaskUuid()) {
          bitField0_ |= 0x00000001;
          taskUuid_ = other.taskUuid_;
          onChanged();
        }
        if (other.hasUuid()) {
          bitField0_ |= 0x00000002;
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.hasDataUuid()) {
          bitField0_ |= 0x00000004;
          dataUuid_ = other.dataUuid_;
          onChanged();
        }
        if (other.hasOccurTime()) {
          setOccurTime(other.getOccurTime());
        }
        if (other.hasRecordNum()) {
          setRecordNum(other.getRecordNum());
        }
        if (other.hasMsgLen()) {
          setMsgLen(other.getMsgLen());
        }
        if (other.hasSaveRecordNum()) {
          setSaveRecordNum(other.getSaveRecordNum());
        }
        if (other.hasFlag()) {
          setFlag(other.getFlag());
        }
        if (other.hasOriginFlag()) {
          setOriginFlag(other.getOriginFlag());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUuid()) {
          return false;
        }
        if (!hasDataUuid()) {
          return false;
        }
        if (!hasOccurTime()) {
          return false;
        }
        if (!hasRecordNum()) {
          return false;
        }
        if (!hasMsgLen()) {
          return false;
        }
        if (!hasOriginFlag()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        excplf_monitor_info parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (excplf_monitor_info) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object taskUuid_ = "";
      /**
       * <pre>
       *��Ӧ�����ʶ��UUID����Դ���ݶ���д��Ŀ��˺���������ӣ�
       * </pre>
       *
       * <code>optional string task_uuid = 1;</code>
       */
      public boolean hasTaskUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *��Ӧ�����ʶ��UUID����Դ���ݶ���д��Ŀ��˺���������ӣ�
       * </pre>
       *
       * <code>optional string task_uuid = 1;</code>
       */
      public String getTaskUuid() {
        Object ref = taskUuid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            taskUuid_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *��Ӧ�����ʶ��UUID����Դ���ݶ���д��Ŀ��˺���������ӣ�
       * </pre>
       *
       * <code>optional string task_uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTaskUuidBytes() {
        Object ref = taskUuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          taskUuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *��Ӧ�����ʶ��UUID����Դ���ݶ���д��Ŀ��˺���������ӣ�
       * </pre>
       *
       * <code>optional string task_uuid = 1;</code>
       */
      public Builder setTaskUuid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        taskUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ӧ�����ʶ��UUID����Դ���ݶ���д��Ŀ��˺���������ӣ�
       * </pre>
       *
       * <code>optional string task_uuid = 1;</code>
       */
      public Builder clearTaskUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        taskUuid_ = getDefaultInstance().getTaskUuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ӧ�����ʶ��UUID����Դ���ݶ���д��Ŀ��˺���������ӣ�
       * </pre>
       *
       * <code>optional string task_uuid = 1;</code>
       */
      public Builder setTaskUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        taskUuid_ = value;
        onChanged();
        return this;
      }

      private Object uuid_ = "";
      /**
       * <pre>
       *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
       * </pre>
       *
       * <code>required string uuid = 2;</code>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
       * </pre>
       *
       * <code>required string uuid = 2;</code>
       */
      public String getUuid() {
        Object ref = uuid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
       * </pre>
       *
       * <code>required string uuid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
       * </pre>
       *
       * <code>required string uuid = 2;</code>
       */
      public Builder setUuid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
       * </pre>
       *
       * <code>required string uuid = 2;</code>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
       * </pre>
       *
       * <code>required string uuid = 2;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uuid_ = value;
        onChanged();
        return this;
      }

      private Object dataUuid_ = "";
      /**
       * <pre>
       *������Ϣ����Ψһ��ʶ��UUID��
       * </pre>
       *
       * <code>required string data_uuid = 3;</code>
       */
      public boolean hasDataUuid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *������Ϣ����Ψһ��ʶ��UUID��
       * </pre>
       *
       * <code>required string data_uuid = 3;</code>
       */
      public String getDataUuid() {
        Object ref = dataUuid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dataUuid_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *������Ϣ����Ψһ��ʶ��UUID��
       * </pre>
       *
       * <code>required string data_uuid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDataUuidBytes() {
        Object ref = dataUuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dataUuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *������Ϣ����Ψһ��ʶ��UUID��
       * </pre>
       *
       * <code>required string data_uuid = 3;</code>
       */
      public Builder setDataUuid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dataUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *������Ϣ����Ψһ��ʶ��UUID��
       * </pre>
       *
       * <code>required string data_uuid = 3;</code>
       */
      public Builder clearDataUuid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dataUuid_ = getDefaultInstance().getDataUuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *������Ϣ����Ψһ��ʶ��UUID��
       * </pre>
       *
       * <code>required string data_uuid = 3;</code>
       */
      public Builder setDataUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dataUuid_ = value;
        onChanged();
        return this;
      }

      private long occurTime_ ;
      /**
       * <pre>
       *Դ��������ʱ�䣨Ŀ��˴���ʱ�䣩����ȷ���룬��1970�꿪ʼ
       * </pre>
       *
       * <code>required int64 occur_time = 4;</code>
       */
      public boolean hasOccurTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *Դ��������ʱ�䣨Ŀ��˴���ʱ�䣩����ȷ���룬��1970�꿪ʼ
       * </pre>
       *
       * <code>required int64 occur_time = 4;</code>
       */
      public long getOccurTime() {
        return occurTime_;
      }
      /**
       * <pre>
       *Դ��������ʱ�䣨Ŀ��˴���ʱ�䣩����ȷ���룬��1970�꿪ʼ
       * </pre>
       *
       * <code>required int64 occur_time = 4;</code>
       */
      public Builder setOccurTime(long value) {
        bitField0_ |= 0x00000008;
        occurTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Դ��������ʱ�䣨Ŀ��˴���ʱ�䣩����ȷ���룬��1970�꿪ʼ
       * </pre>
       *
       * <code>required int64 occur_time = 4;</code>
       */
      public Builder clearOccurTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        occurTime_ = 0L;
        onChanged();
        return this;
      }

      private int recordNum_ ;
      /**
       * <pre>
       *Դ���ݶ��������ݼ�¼����Ŀ����յ�����Ϣ����¼����
       * </pre>
       *
       * <code>required int32 record_num = 5;</code>
       */
      public boolean hasRecordNum() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       *Դ���ݶ��������ݼ�¼����Ŀ����յ�����Ϣ����¼����
       * </pre>
       *
       * <code>required int32 record_num = 5;</code>
       */
      public int getRecordNum() {
        return recordNum_;
      }
      /**
       * <pre>
       *Դ���ݶ��������ݼ�¼����Ŀ����յ�����Ϣ����¼����
       * </pre>
       *
       * <code>required int32 record_num = 5;</code>
       */
      public Builder setRecordNum(int value) {
        bitField0_ |= 0x00000010;
        recordNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Դ���ݶ��������ݼ�¼����Ŀ����յ�����Ϣ����¼����
       * </pre>
       *
       * <code>required int32 record_num = 5;</code>
       */
      public Builder clearRecordNum() {
        bitField0_ = (bitField0_ & ~0x00000010);
        recordNum_ = 0;
        onChanged();
        return this;
      }

      private int msgLen_ ;
      /**
       * <pre>
       *��Ϣ���ĵĴ�С
       * </pre>
       *
       * <code>required int32 msg_len = 6;</code>
       */
      public boolean hasMsgLen() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       *��Ϣ���ĵĴ�С
       * </pre>
       *
       * <code>required int32 msg_len = 6;</code>
       */
      public int getMsgLen() {
        return msgLen_;
      }
      /**
       * <pre>
       *��Ϣ���ĵĴ�С
       * </pre>
       *
       * <code>required int32 msg_len = 6;</code>
       */
      public Builder setMsgLen(int value) {
        bitField0_ |= 0x00000020;
        msgLen_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ϣ���ĵĴ�С
       * </pre>
       *
       * <code>required int32 msg_len = 6;</code>
       */
      public Builder clearMsgLen() {
        bitField0_ = (bitField0_ & ~0x00000020);
        msgLen_ = 0;
        onChanged();
        return this;
      }

      private int saveRecordNum_ ;
      /**
       * <pre>
       *Ŀ�������¼��
       * </pre>
       *
       * <code>optional int32 save_record_num = 7;</code>
       */
      public boolean hasSaveRecordNum() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       *Ŀ�������¼��
       * </pre>
       *
       * <code>optional int32 save_record_num = 7;</code>
       */
      public int getSaveRecordNum() {
        return saveRecordNum_;
      }
      /**
       * <pre>
       *Ŀ�������¼��
       * </pre>
       *
       * <code>optional int32 save_record_num = 7;</code>
       */
      public Builder setSaveRecordNum(int value) {
        bitField0_ |= 0x00000040;
        saveRecordNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Ŀ�������¼��
       * </pre>
       *
       * <code>optional int32 save_record_num = 7;</code>
       */
      public Builder clearSaveRecordNum() {
        bitField0_ = (bitField0_ & ~0x00000040);
        saveRecordNum_ = 0;
        onChanged();
        return this;
      }

      private int flag_ ;
      /**
       * <pre>
       *�������� ��0--������1--����
       * </pre>
       *
       * <code>optional int32 flag = 8;</code>
       */
      public boolean hasFlag() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <pre>
       *�������� ��0--������1--����
       * </pre>
       *
       * <code>optional int32 flag = 8;</code>
       */
      public int getFlag() {
        return flag_;
      }
      /**
       * <pre>
       *�������� ��0--������1--����
       * </pre>
       *
       * <code>optional int32 flag = 8;</code>
       */
      public Builder setFlag(int value) {
        bitField0_ |= 0x00000080;
        flag_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�������� ��0--������1--����
       * </pre>
       *
       * <code>optional int32 flag = 8;</code>
       */
      public Builder clearFlag() {
        bitField0_ = (bitField0_ & ~0x00000080);
        flag_ = 0;
        onChanged();
        return this;
      }

      private int originFlag_ ;
      /**
       * <pre>
       *��Դ ��0--Դ���ݶˣ�1--Ŀ���
       * </pre>
       *
       * <code>required int32 origin_flag = 9;</code>
       */
      public boolean hasOriginFlag() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <pre>
       *��Դ ��0--Դ���ݶˣ�1--Ŀ���
       * </pre>
       *
       * <code>required int32 origin_flag = 9;</code>
       */
      public int getOriginFlag() {
        return originFlag_;
      }
      /**
       * <pre>
       *��Դ ��0--Դ���ݶˣ�1--Ŀ���
       * </pre>
       *
       * <code>required int32 origin_flag = 9;</code>
       */
      public Builder setOriginFlag(int value) {
        bitField0_ |= 0x00000100;
        originFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Դ ��0--Դ���ݶˣ�1--Ŀ���
       * </pre>
       *
       * <code>required int32 origin_flag = 9;</code>
       */
      public Builder clearOriginFlag() {
        bitField0_ = (bitField0_ & ~0x00000100);
        originFlag_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:excplf_monitor_info)
    }

    // @@protoc_insertion_point(class_scope:excplf_monitor_info)
    private static final excplf_monitor_info DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new excplf_monitor_info();
    }

    public static excplf_monitor_info getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<excplf_monitor_info>
        PARSER = new com.google.protobuf.AbstractParser<excplf_monitor_info>() {
      public excplf_monitor_info parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new excplf_monitor_info(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<excplf_monitor_info> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<excplf_monitor_info> getParserForType() {
      return PARSER;
    }

    public excplf_monitor_info getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_excplf_monitor_info_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_excplf_monitor_info_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\033ExchangePlfMonitorMsg.proto\"\276\001\n\023excplf" +
      "_monitor_info\022\021\n\ttask_uuid\030\001 \001(\t\022\014\n\004uuid" +
      "\030\002 \002(\t\022\021\n\tdata_uuid\030\003 \002(\t\022\022\n\noccur_time\030" +
      "\004 \002(\003\022\022\n\nrecord_num\030\005 \002(\005\022\017\n\007msg_len\030\006 \002" +
      "(\005\022\027\n\017save_record_num\030\007 \001(\005\022\014\n\004flag\030\010 \001(" +
      "\005\022\023\n\013origin_flag\030\t \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_excplf_monitor_info_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_excplf_monitor_info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_excplf_monitor_info_descriptor,
        new String[] { "TaskUuid", "Uuid", "DataUuid", "OccurTime", "RecordNum", "MsgLen", "SaveRecordNum", "Flag", "OriginFlag", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
