package com.sgcc.epri.dataexchangeplatform.ProtoJava;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExchangePlfHeartBeat.proto

public final class ExchangePlfHeartBeat {
  private ExchangePlfHeartBeat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *��������
   * </pre>
   *
   * Protobuf enum {@code excplf_heartbeat_operation}
   */
  public enum excplf_heartbeat_operation
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *�����㲥   ���ݽ���ƽ̨�㲥����
     * </pre>
     *
     * <code>EXCPLF_HEART_BROADCAST = 1;</code>
     */
    EXCPLF_HEART_BROADCAST(1),
    /**
     * <pre>
     *������Ӧ   Դ��  Ŀ�����Ӧ  ����������ƽ̨
     * </pre>
     *
     * <code>EXCPLF_HEART_RESPONSE = 2;</code>
     */
    EXCPLF_HEART_RESPONSE(2),
    /**
     * <pre>
     *ָ����������ȡ
     * </pre>
     *
     * <code>EXCPLF_HEART_GET = 3;</code>
     */
    EXCPLF_HEART_GET(3),
    ;

    /**
     * <pre>
     *�����㲥   ���ݽ���ƽ̨�㲥����
     * </pre>
     *
     * <code>EXCPLF_HEART_BROADCAST = 1;</code>
     */
    public static final int EXCPLF_HEART_BROADCAST_VALUE = 1;
    /**
     * <pre>
     *������Ӧ   Դ��  Ŀ�����Ӧ  ����������ƽ̨
     * </pre>
     *
     * <code>EXCPLF_HEART_RESPONSE = 2;</code>
     */
    public static final int EXCPLF_HEART_RESPONSE_VALUE = 2;
    /**
     * <pre>
     *ָ����������ȡ
     * </pre>
     *
     * <code>EXCPLF_HEART_GET = 3;</code>
     */
    public static final int EXCPLF_HEART_GET_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static excplf_heartbeat_operation valueOf(int value) {
      return forNumber(value);
    }

    public static excplf_heartbeat_operation forNumber(int value) {
      switch (value) {
        case 1: return EXCPLF_HEART_BROADCAST;
        case 2: return EXCPLF_HEART_RESPONSE;
        case 3: return EXCPLF_HEART_GET;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<excplf_heartbeat_operation>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        excplf_heartbeat_operation> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<excplf_heartbeat_operation>() {
            public excplf_heartbeat_operation findValueByNumber(int number) {
              return excplf_heartbeat_operation.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ExchangePlfHeartBeat.getDescriptor().getEnumTypes().get(0);
    }

    private static final excplf_heartbeat_operation[] VALUES = values();

    public static excplf_heartbeat_operation valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private excplf_heartbeat_operation(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:excplf_heartbeat_operation)
  }

  public interface excplf_heartbeat_infoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:excplf_heartbeat_info)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
     * </pre>
     *
     * <code>required string uuid = 1;</code>
     */
    boolean hasUuid();
    /**
     * <pre>
     *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
     * </pre>
     *
     * <code>required string uuid = 1;</code>
     */
    String getUuid();
    /**
     * <pre>
     *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
     * </pre>
     *
     * <code>required string uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <pre>
     *�������Ʊ���uuid
     * </pre>
     *
     * <code>optional string heartbeat_uuid = 2;</code>
     */
    boolean hasHeartbeatUuid();
    /**
     * <pre>
     *�������Ʊ���uuid
     * </pre>
     *
     * <code>optional string heartbeat_uuid = 2;</code>
     */
    String getHeartbeatUuid();
    /**
     * <pre>
     *�������Ʊ���uuid
     * </pre>
     *
     * <code>optional string heartbeat_uuid = 2;</code>
     */
    com.google.protobuf.ByteString
        getHeartbeatUuidBytes();

    /**
     * <pre>
     *�����㱨ʱ�䣨�룩
     * </pre>
     *
     * <code>optional int64 occur_time = 3;</code>
     */
    boolean hasOccurTime();
    /**
     * <pre>
     *�����㱨ʱ�䣨�룩
     * </pre>
     *
     * <code>optional int64 occur_time = 3;</code>
     */
    long getOccurTime();

    /**
     * <pre>
     *�������ͷ��࣬����Ŀǰ��������ƽ̨��״���֣���������--0���澯����--1�������������¼�--2������--3���ƻ�Ԥ��--4
     * </pre>
     *
     * <code>optional int32 category_id = 4;</code>
     */
    boolean hasCategoryId();
    /**
     * <pre>
     *�������ͷ��࣬����Ŀǰ��������ƽ̨��״���֣���������--0���澯����--1�������������¼�--2������--3���ƻ�Ԥ��--4
     * </pre>
     *
     * <code>optional int32 category_id = 4;</code>
     */
    int getCategoryId();
  }
  /**
   * <pre>
   *��������
   * </pre>
   *
   * Protobuf type {@code excplf_heartbeat_info}
   */
  public  static final class excplf_heartbeat_info extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:excplf_heartbeat_info)
      excplf_heartbeat_infoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use excplf_heartbeat_info.newBuilder() to construct.
    private excplf_heartbeat_info(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private excplf_heartbeat_info() {
      uuid_ = "";
      heartbeatUuid_ = "";
      occurTime_ = 0L;
      categoryId_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private excplf_heartbeat_info(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uuid_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              heartbeatUuid_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              occurTime_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              categoryId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ExchangePlfHeartBeat.internal_static_excplf_heartbeat_info_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ExchangePlfHeartBeat.internal_static_excplf_heartbeat_info_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              excplf_heartbeat_info.class, Builder.class);
    }

    private int bitField0_;
    public static final int UUID_FIELD_NUMBER = 1;
    private volatile Object uuid_;
    /**
     * <pre>
     *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
     * </pre>
     *
     * <code>required string uuid = 1;</code>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
     * </pre>
     *
     * <code>required string uuid = 1;</code>
     */
    public String getUuid() {
      Object ref = uuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
     * </pre>
     *
     * <code>required string uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEARTBEAT_UUID_FIELD_NUMBER = 2;
    private volatile Object heartbeatUuid_;
    /**
     * <pre>
     *�������Ʊ���uuid
     * </pre>
     *
     * <code>optional string heartbeat_uuid = 2;</code>
     */
    public boolean hasHeartbeatUuid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *�������Ʊ���uuid
     * </pre>
     *
     * <code>optional string heartbeat_uuid = 2;</code>
     */
    public String getHeartbeatUuid() {
      Object ref = heartbeatUuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          heartbeatUuid_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *�������Ʊ���uuid
     * </pre>
     *
     * <code>optional string heartbeat_uuid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHeartbeatUuidBytes() {
      Object ref = heartbeatUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        heartbeatUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OCCUR_TIME_FIELD_NUMBER = 3;
    private long occurTime_;
    /**
     * <pre>
     *�����㱨ʱ�䣨�룩
     * </pre>
     *
     * <code>optional int64 occur_time = 3;</code>
     */
    public boolean hasOccurTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *�����㱨ʱ�䣨�룩
     * </pre>
     *
     * <code>optional int64 occur_time = 3;</code>
     */
    public long getOccurTime() {
      return occurTime_;
    }

    public static final int CATEGORY_ID_FIELD_NUMBER = 4;
    private int categoryId_;
    /**
     * <pre>
     *�������ͷ��࣬����Ŀǰ��������ƽ̨��״���֣���������--0���澯����--1�������������¼�--2������--3���ƻ�Ԥ��--4
     * </pre>
     *
     * <code>optional int32 category_id = 4;</code>
     */
    public boolean hasCategoryId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *�������ͷ��࣬����Ŀǰ��������ƽ̨��״���֣���������--0���澯����--1�������������¼�--2������--3���ƻ�Ԥ��--4
     * </pre>
     *
     * <code>optional int32 category_id = 4;</code>
     */
    public int getCategoryId() {
      return categoryId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, heartbeatUuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, occurTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, categoryId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, heartbeatUuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, occurTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, categoryId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof excplf_heartbeat_info)) {
        return super.equals(obj);
      }
      excplf_heartbeat_info other = (excplf_heartbeat_info) obj;

      boolean result = true;
      result = result && (hasUuid() == other.hasUuid());
      if (hasUuid()) {
        result = result && getUuid()
            .equals(other.getUuid());
      }
      result = result && (hasHeartbeatUuid() == other.hasHeartbeatUuid());
      if (hasHeartbeatUuid()) {
        result = result && getHeartbeatUuid()
            .equals(other.getHeartbeatUuid());
      }
      result = result && (hasOccurTime() == other.hasOccurTime());
      if (hasOccurTime()) {
        result = result && (getOccurTime()
            == other.getOccurTime());
      }
      result = result && (hasCategoryId() == other.hasCategoryId());
      if (hasCategoryId()) {
        result = result && (getCategoryId()
            == other.getCategoryId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUuid()) {
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
      }
      if (hasHeartbeatUuid()) {
        hash = (37 * hash) + HEARTBEAT_UUID_FIELD_NUMBER;
        hash = (53 * hash) + getHeartbeatUuid().hashCode();
      }
      if (hasOccurTime()) {
        hash = (37 * hash) + OCCUR_TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getOccurTime());
      }
      if (hasCategoryId()) {
        hash = (37 * hash) + CATEGORY_ID_FIELD_NUMBER;
        hash = (53 * hash) + getCategoryId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static excplf_heartbeat_info parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static excplf_heartbeat_info parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static excplf_heartbeat_info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static excplf_heartbeat_info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static excplf_heartbeat_info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static excplf_heartbeat_info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static excplf_heartbeat_info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static excplf_heartbeat_info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static excplf_heartbeat_info parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static excplf_heartbeat_info parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static excplf_heartbeat_info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static excplf_heartbeat_info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(excplf_heartbeat_info prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *��������
     * </pre>
     *
     * Protobuf type {@code excplf_heartbeat_info}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:excplf_heartbeat_info)
        excplf_heartbeat_infoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ExchangePlfHeartBeat.internal_static_excplf_heartbeat_info_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ExchangePlfHeartBeat.internal_static_excplf_heartbeat_info_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                excplf_heartbeat_info.class, Builder.class);
      }

      // Construct using ExchangePlfHeartBeat.excplf_heartbeat_info.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        heartbeatUuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        occurTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        categoryId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ExchangePlfHeartBeat.internal_static_excplf_heartbeat_info_descriptor;
      }

      public excplf_heartbeat_info getDefaultInstanceForType() {
        return excplf_heartbeat_info.getDefaultInstance();
      }

      public excplf_heartbeat_info build() {
        excplf_heartbeat_info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public excplf_heartbeat_info buildPartial() {
        excplf_heartbeat_info result = new excplf_heartbeat_info(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.heartbeatUuid_ = heartbeatUuid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.occurTime_ = occurTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.categoryId_ = categoryId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof excplf_heartbeat_info) {
          return mergeFrom((excplf_heartbeat_info)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(excplf_heartbeat_info other) {
        if (other == excplf_heartbeat_info.getDefaultInstance()) return this;
        if (other.hasUuid()) {
          bitField0_ |= 0x00000001;
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.hasHeartbeatUuid()) {
          bitField0_ |= 0x00000002;
          heartbeatUuid_ = other.heartbeatUuid_;
          onChanged();
        }
        if (other.hasOccurTime()) {
          setOccurTime(other.getOccurTime());
        }
        if (other.hasCategoryId()) {
          setCategoryId(other.getCategoryId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUuid()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        excplf_heartbeat_info parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (excplf_heartbeat_info) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object uuid_ = "";
      /**
       * <pre>
       *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
       * </pre>
       *
       * <code>required string uuid = 1;</code>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
       * </pre>
       *
       * <code>required string uuid = 1;</code>
       */
      public String getUuid() {
        Object ref = uuid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
       * </pre>
       *
       * <code>required string uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
       * </pre>
       *
       * <code>required string uuid = 1;</code>
       */
      public Builder setUuid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
       * </pre>
       *
       * <code>required string uuid = 1;</code>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Դ���ݶ�(/Ŀ���)Ψһ��ʶ��UUID��
       * </pre>
       *
       * <code>required string uuid = 1;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }

      private Object heartbeatUuid_ = "";
      /**
       * <pre>
       *�������Ʊ���uuid
       * </pre>
       *
       * <code>optional string heartbeat_uuid = 2;</code>
       */
      public boolean hasHeartbeatUuid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *�������Ʊ���uuid
       * </pre>
       *
       * <code>optional string heartbeat_uuid = 2;</code>
       */
      public String getHeartbeatUuid() {
        Object ref = heartbeatUuid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            heartbeatUuid_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *�������Ʊ���uuid
       * </pre>
       *
       * <code>optional string heartbeat_uuid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHeartbeatUuidBytes() {
        Object ref = heartbeatUuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          heartbeatUuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *�������Ʊ���uuid
       * </pre>
       *
       * <code>optional string heartbeat_uuid = 2;</code>
       */
      public Builder setHeartbeatUuid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        heartbeatUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�������Ʊ���uuid
       * </pre>
       *
       * <code>optional string heartbeat_uuid = 2;</code>
       */
      public Builder clearHeartbeatUuid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        heartbeatUuid_ = getDefaultInstance().getHeartbeatUuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�������Ʊ���uuid
       * </pre>
       *
       * <code>optional string heartbeat_uuid = 2;</code>
       */
      public Builder setHeartbeatUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        heartbeatUuid_ = value;
        onChanged();
        return this;
      }

      private long occurTime_ ;
      /**
       * <pre>
       *�����㱨ʱ�䣨�룩
       * </pre>
       *
       * <code>optional int64 occur_time = 3;</code>
       */
      public boolean hasOccurTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *�����㱨ʱ�䣨�룩
       * </pre>
       *
       * <code>optional int64 occur_time = 3;</code>
       */
      public long getOccurTime() {
        return occurTime_;
      }
      /**
       * <pre>
       *�����㱨ʱ�䣨�룩
       * </pre>
       *
       * <code>optional int64 occur_time = 3;</code>
       */
      public Builder setOccurTime(long value) {
        bitField0_ |= 0x00000004;
        occurTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�����㱨ʱ�䣨�룩
       * </pre>
       *
       * <code>optional int64 occur_time = 3;</code>
       */
      public Builder clearOccurTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        occurTime_ = 0L;
        onChanged();
        return this;
      }

      private int categoryId_ ;
      /**
       * <pre>
       *�������ͷ��࣬����Ŀǰ��������ƽ̨��״���֣���������--0���澯����--1�������������¼�--2������--3���ƻ�Ԥ��--4
       * </pre>
       *
       * <code>optional int32 category_id = 4;</code>
       */
      public boolean hasCategoryId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *�������ͷ��࣬����Ŀǰ��������ƽ̨��״���֣���������--0���澯����--1�������������¼�--2������--3���ƻ�Ԥ��--4
       * </pre>
       *
       * <code>optional int32 category_id = 4;</code>
       */
      public int getCategoryId() {
        return categoryId_;
      }
      /**
       * <pre>
       *�������ͷ��࣬����Ŀǰ��������ƽ̨��״���֣���������--0���澯����--1�������������¼�--2������--3���ƻ�Ԥ��--4
       * </pre>
       *
       * <code>optional int32 category_id = 4;</code>
       */
      public Builder setCategoryId(int value) {
        bitField0_ |= 0x00000008;
        categoryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�������ͷ��࣬����Ŀǰ��������ƽ̨��״���֣���������--0���澯����--1�������������¼�--2������--3���ƻ�Ԥ��--4
       * </pre>
       *
       * <code>optional int32 category_id = 4;</code>
       */
      public Builder clearCategoryId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        categoryId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:excplf_heartbeat_info)
    }

    // @@protoc_insertion_point(class_scope:excplf_heartbeat_info)
    private static final excplf_heartbeat_info DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new excplf_heartbeat_info();
    }

    public static excplf_heartbeat_info getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<excplf_heartbeat_info>
        PARSER = new com.google.protobuf.AbstractParser<excplf_heartbeat_info>() {
      public excplf_heartbeat_info parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new excplf_heartbeat_info(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<excplf_heartbeat_info> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<excplf_heartbeat_info> getParserForType() {
      return PARSER;
    }

    public excplf_heartbeat_info getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface excplf_heartbeat_msgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:excplf_heartbeat_msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *�������Ĳ�������
     * </pre>
     *
     * <code>required .excplf_heartbeat_operation oper = 1;</code>
     */
    boolean hasOper();
    /**
     * <pre>
     *�������Ĳ�������
     * </pre>
     *
     * <code>required .excplf_heartbeat_operation oper = 1;</code>
     */
    excplf_heartbeat_operation getOper();

    /**
     * <pre>
     *������Ϣ   ����ȷ����������������
     * </pre>
     *
     * <code>optional .excplf_heartbeat_info heartbeat_info = 2;</code>
     */
    boolean hasHeartbeatInfo();
    /**
     * <pre>
     *������Ϣ   ����ȷ����������������
     * </pre>
     *
     * <code>optional .excplf_heartbeat_info heartbeat_info = 2;</code>
     */
    excplf_heartbeat_info getHeartbeatInfo();
    /**
     * <pre>
     *������Ϣ   ����ȷ����������������
     * </pre>
     *
     * <code>optional .excplf_heartbeat_info heartbeat_info = 2;</code>
     */
    excplf_heartbeat_infoOrBuilder getHeartbeatInfoOrBuilder();
  }
  /**
   * <pre>
   *�������䱨����
   * </pre>
   *
   * Protobuf type {@code excplf_heartbeat_msg}
   */
  public  static final class excplf_heartbeat_msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:excplf_heartbeat_msg)
      excplf_heartbeat_msgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use excplf_heartbeat_msg.newBuilder() to construct.
    private excplf_heartbeat_msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private excplf_heartbeat_msg() {
      oper_ = 1;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private excplf_heartbeat_msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              excplf_heartbeat_operation value = excplf_heartbeat_operation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                oper_ = rawValue;
              }
              break;
            }
            case 18: {
              excplf_heartbeat_info.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = heartbeatInfo_.toBuilder();
              }
              heartbeatInfo_ = input.readMessage(excplf_heartbeat_info.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(heartbeatInfo_);
                heartbeatInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ExchangePlfHeartBeat.internal_static_excplf_heartbeat_msg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ExchangePlfHeartBeat.internal_static_excplf_heartbeat_msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              excplf_heartbeat_msg.class, Builder.class);
    }

    private int bitField0_;
    public static final int OPER_FIELD_NUMBER = 1;
    private int oper_;
    /**
     * <pre>
     *�������Ĳ�������
     * </pre>
     *
     * <code>required .excplf_heartbeat_operation oper = 1;</code>
     */
    public boolean hasOper() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *�������Ĳ�������
     * </pre>
     *
     * <code>required .excplf_heartbeat_operation oper = 1;</code>
     */
    public excplf_heartbeat_operation getOper() {
      excplf_heartbeat_operation result = excplf_heartbeat_operation.valueOf(oper_);
      return result == null ? excplf_heartbeat_operation.EXCPLF_HEART_BROADCAST : result;
    }

    public static final int HEARTBEAT_INFO_FIELD_NUMBER = 2;
    private excplf_heartbeat_info heartbeatInfo_;
    /**
     * <pre>
     *������Ϣ   ����ȷ����������������
     * </pre>
     *
     * <code>optional .excplf_heartbeat_info heartbeat_info = 2;</code>
     */
    public boolean hasHeartbeatInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *������Ϣ   ����ȷ����������������
     * </pre>
     *
     * <code>optional .excplf_heartbeat_info heartbeat_info = 2;</code>
     */
    public excplf_heartbeat_info getHeartbeatInfo() {
      return heartbeatInfo_ == null ? excplf_heartbeat_info.getDefaultInstance() : heartbeatInfo_;
    }
    /**
     * <pre>
     *������Ϣ   ����ȷ����������������
     * </pre>
     *
     * <code>optional .excplf_heartbeat_info heartbeat_info = 2;</code>
     */
    public excplf_heartbeat_infoOrBuilder getHeartbeatInfoOrBuilder() {
      return heartbeatInfo_ == null ? excplf_heartbeat_info.getDefaultInstance() : heartbeatInfo_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOper()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasHeartbeatInfo()) {
        if (!getHeartbeatInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, oper_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getHeartbeatInfo());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, oper_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getHeartbeatInfo());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof excplf_heartbeat_msg)) {
        return super.equals(obj);
      }
      excplf_heartbeat_msg other = (excplf_heartbeat_msg) obj;

      boolean result = true;
      result = result && (hasOper() == other.hasOper());
      if (hasOper()) {
        result = result && oper_ == other.oper_;
      }
      result = result && (hasHeartbeatInfo() == other.hasHeartbeatInfo());
      if (hasHeartbeatInfo()) {
        result = result && getHeartbeatInfo()
            .equals(other.getHeartbeatInfo());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOper()) {
        hash = (37 * hash) + OPER_FIELD_NUMBER;
        hash = (53 * hash) + oper_;
      }
      if (hasHeartbeatInfo()) {
        hash = (37 * hash) + HEARTBEAT_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getHeartbeatInfo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static excplf_heartbeat_msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static excplf_heartbeat_msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static excplf_heartbeat_msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static excplf_heartbeat_msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static excplf_heartbeat_msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static excplf_heartbeat_msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static excplf_heartbeat_msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static excplf_heartbeat_msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static excplf_heartbeat_msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static excplf_heartbeat_msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static excplf_heartbeat_msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static excplf_heartbeat_msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(excplf_heartbeat_msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *�������䱨����
     * </pre>
     *
     * Protobuf type {@code excplf_heartbeat_msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:excplf_heartbeat_msg)
        excplf_heartbeat_msgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ExchangePlfHeartBeat.internal_static_excplf_heartbeat_msg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ExchangePlfHeartBeat.internal_static_excplf_heartbeat_msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                excplf_heartbeat_msg.class, Builder.class);
      }

      // Construct using ExchangePlfHeartBeat.excplf_heartbeat_msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHeartbeatInfoFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        oper_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (heartbeatInfoBuilder_ == null) {
          heartbeatInfo_ = null;
        } else {
          heartbeatInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ExchangePlfHeartBeat.internal_static_excplf_heartbeat_msg_descriptor;
      }

      public excplf_heartbeat_msg getDefaultInstanceForType() {
        return excplf_heartbeat_msg.getDefaultInstance();
      }

      public excplf_heartbeat_msg build() {
        excplf_heartbeat_msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public excplf_heartbeat_msg buildPartial() {
        excplf_heartbeat_msg result = new excplf_heartbeat_msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.oper_ = oper_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (heartbeatInfoBuilder_ == null) {
          result.heartbeatInfo_ = heartbeatInfo_;
        } else {
          result.heartbeatInfo_ = heartbeatInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof excplf_heartbeat_msg) {
          return mergeFrom((excplf_heartbeat_msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(excplf_heartbeat_msg other) {
        if (other == excplf_heartbeat_msg.getDefaultInstance()) return this;
        if (other.hasOper()) {
          setOper(other.getOper());
        }
        if (other.hasHeartbeatInfo()) {
          mergeHeartbeatInfo(other.getHeartbeatInfo());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOper()) {
          return false;
        }
        if (hasHeartbeatInfo()) {
          if (!getHeartbeatInfo().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        excplf_heartbeat_msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (excplf_heartbeat_msg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int oper_ = 1;
      /**
       * <pre>
       *�������Ĳ�������
       * </pre>
       *
       * <code>required .excplf_heartbeat_operation oper = 1;</code>
       */
      public boolean hasOper() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *�������Ĳ�������
       * </pre>
       *
       * <code>required .excplf_heartbeat_operation oper = 1;</code>
       */
      public excplf_heartbeat_operation getOper() {
        excplf_heartbeat_operation result = excplf_heartbeat_operation.valueOf(oper_);
        return result == null ? excplf_heartbeat_operation.EXCPLF_HEART_BROADCAST : result;
      }
      /**
       * <pre>
       *�������Ĳ�������
       * </pre>
       *
       * <code>required .excplf_heartbeat_operation oper = 1;</code>
       */
      public Builder setOper(excplf_heartbeat_operation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        oper_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�������Ĳ�������
       * </pre>
       *
       * <code>required .excplf_heartbeat_operation oper = 1;</code>
       */
      public Builder clearOper() {
        bitField0_ = (bitField0_ & ~0x00000001);
        oper_ = 1;
        onChanged();
        return this;
      }

      private excplf_heartbeat_info heartbeatInfo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          excplf_heartbeat_info, excplf_heartbeat_info.Builder, excplf_heartbeat_infoOrBuilder> heartbeatInfoBuilder_;
      /**
       * <pre>
       *������Ϣ   ����ȷ����������������
       * </pre>
       *
       * <code>optional .excplf_heartbeat_info heartbeat_info = 2;</code>
       */
      public boolean hasHeartbeatInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *������Ϣ   ����ȷ����������������
       * </pre>
       *
       * <code>optional .excplf_heartbeat_info heartbeat_info = 2;</code>
       */
      public excplf_heartbeat_info getHeartbeatInfo() {
        if (heartbeatInfoBuilder_ == null) {
          return heartbeatInfo_ == null ? excplf_heartbeat_info.getDefaultInstance() : heartbeatInfo_;
        } else {
          return heartbeatInfoBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *������Ϣ   ����ȷ����������������
       * </pre>
       *
       * <code>optional .excplf_heartbeat_info heartbeat_info = 2;</code>
       */
      public Builder setHeartbeatInfo(excplf_heartbeat_info value) {
        if (heartbeatInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          heartbeatInfo_ = value;
          onChanged();
        } else {
          heartbeatInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *������Ϣ   ����ȷ����������������
       * </pre>
       *
       * <code>optional .excplf_heartbeat_info heartbeat_info = 2;</code>
       */
      public Builder setHeartbeatInfo(
          excplf_heartbeat_info.Builder builderForValue) {
        if (heartbeatInfoBuilder_ == null) {
          heartbeatInfo_ = builderForValue.build();
          onChanged();
        } else {
          heartbeatInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *������Ϣ   ����ȷ����������������
       * </pre>
       *
       * <code>optional .excplf_heartbeat_info heartbeat_info = 2;</code>
       */
      public Builder mergeHeartbeatInfo(excplf_heartbeat_info value) {
        if (heartbeatInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              heartbeatInfo_ != null &&
              heartbeatInfo_ != excplf_heartbeat_info.getDefaultInstance()) {
            heartbeatInfo_ =
              excplf_heartbeat_info.newBuilder(heartbeatInfo_).mergeFrom(value).buildPartial();
          } else {
            heartbeatInfo_ = value;
          }
          onChanged();
        } else {
          heartbeatInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *������Ϣ   ����ȷ����������������
       * </pre>
       *
       * <code>optional .excplf_heartbeat_info heartbeat_info = 2;</code>
       */
      public Builder clearHeartbeatInfo() {
        if (heartbeatInfoBuilder_ == null) {
          heartbeatInfo_ = null;
          onChanged();
        } else {
          heartbeatInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <pre>
       *������Ϣ   ����ȷ����������������
       * </pre>
       *
       * <code>optional .excplf_heartbeat_info heartbeat_info = 2;</code>
       */
      public excplf_heartbeat_info.Builder getHeartbeatInfoBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getHeartbeatInfoFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *������Ϣ   ����ȷ����������������
       * </pre>
       *
       * <code>optional .excplf_heartbeat_info heartbeat_info = 2;</code>
       */
      public excplf_heartbeat_infoOrBuilder getHeartbeatInfoOrBuilder() {
        if (heartbeatInfoBuilder_ != null) {
          return heartbeatInfoBuilder_.getMessageOrBuilder();
        } else {
          return heartbeatInfo_ == null ?
              excplf_heartbeat_info.getDefaultInstance() : heartbeatInfo_;
        }
      }
      /**
       * <pre>
       *������Ϣ   ����ȷ����������������
       * </pre>
       *
       * <code>optional .excplf_heartbeat_info heartbeat_info = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          excplf_heartbeat_info, excplf_heartbeat_info.Builder, excplf_heartbeat_infoOrBuilder>
          getHeartbeatInfoFieldBuilder() {
        if (heartbeatInfoBuilder_ == null) {
          heartbeatInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              excplf_heartbeat_info, excplf_heartbeat_info.Builder, excplf_heartbeat_infoOrBuilder>(
                  getHeartbeatInfo(),
                  getParentForChildren(),
                  isClean());
          heartbeatInfo_ = null;
        }
        return heartbeatInfoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:excplf_heartbeat_msg)
    }

    // @@protoc_insertion_point(class_scope:excplf_heartbeat_msg)
    private static final excplf_heartbeat_msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new excplf_heartbeat_msg();
    }

    public static excplf_heartbeat_msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<excplf_heartbeat_msg>
        PARSER = new com.google.protobuf.AbstractParser<excplf_heartbeat_msg>() {
      public excplf_heartbeat_msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new excplf_heartbeat_msg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<excplf_heartbeat_msg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<excplf_heartbeat_msg> getParserForType() {
      return PARSER;
    }

    public excplf_heartbeat_msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_excplf_heartbeat_info_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_excplf_heartbeat_info_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_excplf_heartbeat_msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_excplf_heartbeat_msg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\032ExchangePlfHeartBeat.proto\"f\n\025excplf_h" +
      "eartbeat_info\022\014\n\004uuid\030\001 \002(\t\022\026\n\016heartbeat" +
      "_uuid\030\002 \001(\t\022\022\n\noccur_time\030\003 \001(\003\022\023\n\013categ" +
      "ory_id\030\004 \001(\005\"q\n\024excplf_heartbeat_msg\022)\n\004" +
      "oper\030\001 \002(\0162\033.excplf_heartbeat_operation\022" +
      ".\n\016heartbeat_info\030\002 \001(\0132\026.excplf_heartbe" +
      "at_info*i\n\032excplf_heartbeat_operation\022\032\n" +
      "\026EXCPLF_HEART_BROADCAST\020\001\022\031\n\025EXCPLF_HEAR" +
      "T_RESPONSE\020\002\022\024\n\020EXCPLF_HEART_GET\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_excplf_heartbeat_info_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_excplf_heartbeat_info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_excplf_heartbeat_info_descriptor,
        new String[] { "Uuid", "HeartbeatUuid", "OccurTime", "CategoryId", });
    internal_static_excplf_heartbeat_msg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_excplf_heartbeat_msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_excplf_heartbeat_msg_descriptor,
        new String[] { "Oper", "HeartbeatInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
